// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9yZYrFEHk0u8AimmRxi6ImTcneRAPG0o',
    appId: '1:21020361326:web:1e30ff3b34b76d209b1c7f',
    messagingSenderId: '21020361326',
    projectId: 'cards-79845',
    authDomain: 'cards-79845.firebaseapp.com',
    storageBucket: 'cards-79845.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAOksGdPdDj36Bu5rqmRiLnqFi1-CCfqQ',
    appId: '1:21020361326:android:f1cd407356534a729b1c7f',
    messagingSenderId: '21020361326',
    projectId: 'cards-79845',
    storageBucket: 'cards-79845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmDEHUVImRJLAFACezzqWbm1lvB_jawM',
    appId: '1:21020361326:ios:15b6bce8d76d66389b1c7f',
    messagingSenderId: '21020361326',
    projectId: 'cards-79845',
    storageBucket: 'cards-79845.appspot.com',
    iosBundleId: 'com.trejop.mostrarinfocard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmDEHUVImRJLAFACezzqWbm1lvB_jawM',
    appId: '1:21020361326:ios:e08dc09d9909fdac9b1c7f',
    messagingSenderId: '21020361326',
    projectId: 'cards-79845',
    storageBucket: 'cards-79845.appspot.com',
    iosBundleId: 'com.trejop.mostrarinfocard.RunnerTests',
  );
}
